config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  # good_job dashboard path
  authenticate :user, ->(u) { u.isAdmin? } do
    mount GoodJob::Engine => 'good_job'
  end

  # Postgres dashboard path
  if Rails.env.production? || Rails.env.development?
    authenticate :user, lambda { |u| u.isAdmin? } do
      mount PgHero::Engine, at: "pghero"
    end
  end

  root "home_pages#index"

  resources :dashboards, only: [:index]
  resources :remind_mes do
    member do
      delete :delete_from_show_page
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :authenticate_user!
  def index
    current_time = Time.current
    @reminded_you = current_user.remind_mes.where('remind_me_date_time <= ?', current_time).page(params[:reminded_you_page]).per(1)
    @will_remind_you = current_user.remind_mes.where('remind_me_date_time > ?', current_time).page(params[:will_remind_you_page]).per(8)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_reminders_dashboard.html.erb
<div >
  <turbo-frame id="reminders_dashboard">

    <h2 class="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">Reminded You</h2>
    <% if reminded_you.any? %>
      <div class="flex flex-wrap">
        <% reminded_you.each do |remind_me| %>
          <div class="m-2">
            <article class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm transition hover:shadow-lg sm:p-6 dark:border-gray-700 dark:bg-gray-800 dark:shadow-gray-700/25">

              <h3 class="mt-0.5 text-lg font-medium text-gray-900 dark:text-gray-100">Subject: <%= remind_me.subject %></h3>

              <p class="mt-2 line-clamp-3 text-sm/relaxed text-gray-600 dark:text-gray-300">Content: <%= remind_me.content %></p>
              <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Time Zone:</strong> <%= remind_me.remind_me_time_zone %></p>
              <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Reminded You At:</strong> <%= remind_me.remind_me_date_time.in_time_zone(remind_me.remind_me_time_zone).strftime("%B %d, %Y %I:%M %p") %></p>

              <div class="card-actions justify-end mt-4">
                <%= link_to "View", remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
                <%= link_to "Edit", edit_remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
                <%#= button_to "Delete", remind_me_path(remind_me), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
              </div>
            </article>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="text-gray-600 dark:text-gray-300">You have no past reminders.</p>
    <% end %>

    <h2 class="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4 mt-8">Will Remind You</h2>
    <% if will_remind_you.any? %>
      <div class="flex flex-wrap">
        <% will_remind_you.each do |remind_me| %>
          <div class="m-2">
            <article class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm transition hover:shadow-lg sm:p-6 dark:border-gray-700 dark:bg-gray-800 dark:shadow-gray-700/25">

              <h3 class="mt-0.5 text-lg font-medium text-gray-900 dark:text-gray-100">Subject: <%= remind_me.subject %></h3>

              <p class="mt-2 line-clamp-3 text-sm/relaxed text-gray-600 dark:text-gray-300">Content: <%= remind_me.content %></p>
              <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Time Zone:</strong> <%= remind_me.remind_me_time_zone %></p>
              <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Remind Me At:</strong> <%= remind_me.remind_me_date_time.in_time_zone(remind_me.remind_me_time_zone).strftime("%B %d, %Y %I:%M %p") %></p>

              <div class="card-actions justify-end mt-4">
                <%= link_to "View", remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
                <%= link_to "Edit", edit_remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
                <%#= button_to "Delete", remind_me_path(remind_me), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
              </div>
            </article>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="text-gray-600 dark:text-gray-300">You have no upcoming reminders.</p>
    <% end %>
  </turbo-frame>
</div>

app/views/dashboards/index.html.erb
<!--# views/dashboards/index.html.erb-->
<div >
<!--  <turbo-frame id="reminders_dashboard">-->

  <h2 class="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">Reminded You</h2>
  <% if @reminded_you.any? %>
    <div class="flex flex-wrap">
      <% @reminded_you.each do |remind_me| %>
        <div class="m-2">
          <article class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm transition hover:shadow-lg sm:p-6 dark:border-gray-700 dark:bg-gray-800 dark:shadow-gray-700/25">

            <h3 class="mt-0.5 text-lg font-medium text-gray-900 dark:text-gray-100">Subject: <%= remind_me.subject %></h3>

            <p class="mt-2 line-clamp-3 text-sm/relaxed text-gray-600 dark:text-gray-300">Content: <%= remind_me.content %></p>
            <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Time Zone:</strong> <%= remind_me.remind_me_time_zone %></p>
            <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Reminded You At:</strong> <%= remind_me.remind_me_date_time.in_time_zone(remind_me.remind_me_time_zone).strftime("%B %d, %Y %I:%M %p") %></p>

            <div class="card-actions justify-end mt-4">
              <%= link_to "View", remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
              <%= link_to "Edit", edit_remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
              <%#= button_to "Delete", remind_me_path(remind_me), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
            </div>
          </article>
        </div>
      <% end %>
    </div>
<!--      here is pagination-->
      <%= paginate @reminded_you, param_name: 'reminded_you_page' %>
  <% else %>
    <p class="text-gray-600 dark:text-gray-300">You have no past reminders.</p>
  <% end %>

  <h2 class="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4 mt-8">Will Remind You</h2>
  <% if @will_remind_you.any? %>
    <div class="flex flex-wrap">
      <% @will_remind_you.each do |remind_me| %>
        <div class="m-2">
          <article class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm transition hover:shadow-lg sm:p-6 dark:border-gray-700 dark:bg-gray-800 dark:shadow-gray-700/25">

            <h3 class="mt-0.5 text-lg font-medium text-gray-900 dark:text-gray-100">Subject: <%= remind_me.subject %></h3>

            <p class="mt-2 line-clamp-3 text-sm/relaxed text-gray-600 dark:text-gray-300">Content: <%= remind_me.content %></p>
            <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Time Zone:</strong> <%= remind_me.remind_me_time_zone %></p>
            <p class="mt-2 text-sm/relaxed text-gray-600 dark:text-gray-300"><strong>Remind Me At:</strong> <%= remind_me.remind_me_date_time.in_time_zone(remind_me.remind_me_time_zone).strftime("%B %d, %Y %I:%M %p") %></p>

            <div class="card-actions justify-end mt-4">
              <%= link_to "View", remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
              <%= link_to "Edit", edit_remind_me_path(remind_me), data: { turbo_frame: "_top" }, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
              <%#= button_to "Delete", remind_me_path(remind_me), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete, class: "group inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400" %>
            </div>
          </article>
        </div>
      <% end %>
    </div>
    <!--      here is pagination-->
      <%= paginate @will_remind_you, param_name: 'will_remind_you_page' %>
  <% else %>
    <p class="text-gray-600 dark:text-gray-300">You have no upcoming reminders.</p>
  <% end %>
<!--  </turbo-frame>-->
</div>